disable home component impl
AbsaOSS/hyperdrive-trigger pull request #197
Opened 2020-06-09 11:21 UTC by senelesithole

implements #191

rerouting after logging in and on logo click.
component not removed from the project for future works.

2020-06-09 12:50 UTC, jozefbakus approved these changes

2020-06-09 12:50 UTC, jozefbakus commented on ui/src/app/app-routing.module.ts
> +  { path: routeNames.WORKFLOWS_HOME, component: WorkflowsHomeComponent, canActivate: [AuthGuardService] },
You can remove this line

2020-06-09 12:53 UTC, jozefbakus requested changes
One little thing

2020-06-09 12:59 UTC, senelesithole commented on ui/src/app/app-routing.module.ts
> +  { path: routeNames.WORKFLOWS_HOME, component: WorkflowsHomeComponent, canActivate: [AuthGuardService] },
removed.

2020-06-09 13:16 UTC, jozefbakus approved these changes

2020-06-10 09:44 UTC, kevinwallimann approved these changes

2020-06-10 11:10 UTC, merged