init impl
AbsaOSS/hyperdrive-trigger pull request #207
Opened 2020-06-17 08:50 UTC by senelesithole

fix #192

2020-06-17 12:10 UTC, kevinwallimann requested changes
Imo, this doesn't address the root cause of the bug. The problem is probably in the Workflow Reducer, e.g. in the case `WorkflowsActions.DELETE_WORKFLOW_SUCCESS` you can see that old projects are never deleted from the store, unless the whole page is refreshed ofc.
You can see in the screenshot (from redux dev tools) that the rename of the project simply lead to an addition of a new project instance in the store.
![image](https://user-images.githubusercontent.com/54136196/84895588-d1d7e900-b0a2-11ea-81cd-3c566477e8d8.png)
I guess the underlying confusion is because in the data model, `workflowModel.project` is thought to be merely a reference to project, while the definition of the project name is in `ProjectModel.name`. However in the UI, the Project Name input field simultaneously serves as both reference and definition of a project name. Honestly I think we haven't done ourselves a favour to not cleanly separate project definition from usage, but now we have to live with it.

2020-06-19 10:12 UTC, jozefbakus commented on ui/src/app/stores/workflows/workflows.reducers.ts
>          loading: true,
Cool

2020-06-19 10:12 UTC, jozefbakus approved these changes

2020-06-19 11:34 UTC, kevinwallimann approved these changes
That was easier than I expected 👌

2020-06-19 11:38 UTC, jozefbakus commented
> That was easier than I expected 👌

I thought same thing :D

2020-06-19 11:41 UTC, senelesithole commented
The lines of code don't really reflect the complexity of the issue 😊.

so that wasn't easy.

Thanks, Guys.

2020-06-19 11:41 UTC, merged