Impl 214 and wip 215
AbsaOSS/hyperdrive-trigger pull request #232
Opened 2020-07-02 14:41 UTC by senelesithole

fixes #214 and 
WIP #215 

Requires input on.
1. New button on Workflows home, aligned with 'create workflow' button or okay as is.
2. Clear sort functionality.

2020-07-03 07:56 UTC, kevinwallimann reviewed
If I delete /run a workflow, the filters are reset. I think a better approach would be to retain the filters, I guess this could be achieved with onClarityDgRefresh, similarly as in runs.component

2020-07-03 07:56 UTC, kevinwallimann commented on ui/src/app/components/workflows/workflows-home/workflows-home.component.html
> +    <ng-container *clrDgHideableColumn="{hideden: false}">Workflow name</ng-container>
typo: hidden

2020-07-03 07:56 UTC, kevinwallimann commented on ui/src/app/components/workflows/workflows-home/workflows-home.component.html
> +    <ng-container *clrDgHideableColumn="{hideden: false}">Project name</ng-container>
typo hidden

2020-07-03 07:56 UTC, kevinwallimann commented on ui/src/app/components/workflows/workflows-home/workflows-home.component.html
>    <clr-dg-column>Is active</clr-dg-column>
No filter for is active?

2020-07-03 08:00 UTC, kevinwallimann commented on ui/src/app/components/common/datagrid/filters/datetime-range-filter/datetime-range-filter.component.ts
> +import { DagRunModel } from '../../../../../models/dagRuns/dagRun.model';
Interesting that the filters work, even though you're not passing a `DagRunModel`. I'm thinking, if we generalize the filters, then probably the filters should not implement
`ClrDatagridFilterInterface<DagRunModel>`, but `ClrDatagridFilterInterface<any>` instead. The type parameter is only used for the `accepts` method, and there we have a type-unsafe access anyway with `item[this.property]`, i.e. we can't make this component type-safe anyway, so we don't lose anything by replacing `DagRunModel` with `any`

2020-07-08 11:35 UTC, jozefbakus commented on ui/src/app/services/workflow/workflow.service.ts
> +  searchProjects(searchRequestModel: TableSearchRequestModel): Observable<TableSearchResponseModel<ProjectModel>> {
You dont need this because we will sort and filter on FE

2020-07-08 11:40 UTC, jozefbakus requested changes
1. Move filters outside of runs - DONE
2. You dont have to call backend search endpoint for workflows filter/sort
5. You have to persist filters/sorts to store. and use them when page is reloaded 
3. How to pre set sort https://clarity.design/documentation/datagrid/custom-sorting
4. How to pre set filter https://clarity.design/documentation/datagrid/built-in-filters (end of the doc)

2020-07-14 07:17 UTC, jozefbakus reviewed
could you please remove logs/app.log from changes.

2020-07-16 12:56 UTC, closed without merging